baseURL = "https://aea.dev"
languageCode = "en-us"
title = "AEA.dev"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/blog'
  homepage_button_text = 'Read the blog'
  homepage_intro = 'AEA.dev is a site for developers and researchers working with the AEA framework.'
  # homepage_image = 'https://www.youtube.com/watch?v=gvzYX7CYk-A'
  homepage_video = 'https://www.youtube.com/embed/gvzYX7CYk-A'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "AEA.dev is a site for developers and researchers working with the AEA framework."
    meta_og_title = "AEA.dev"
    meta_og_type = "website"
    meta_og_url = "https://aea.dev"
    meta_og_image = ""
    meta_og_description = "AEA.dev is a site for developers and researchers working with the AEA framework."
    meta_twitter_card = "summary"
    meta_twitter_site = "@david_enim"
    meta_twitter_creator = "@david_enim"

  [params.logo]
      mobile = "/images/logo.svg"
      standard  = "/images/logo.svg"
